---
---


It routinely attracts both attention and condemnation, when elected officals leave office to take jobs in the private sector. Despite this, very little is known about the causes and consequences of this so-called revolving door between business and politics. In my dissertation, I investigate how 1) the potential for post-elective employment shapes the behavior of US Members of Congress, and 2) firms that hire former Members of Congress can ...

**The Revolving Door and Taxes -- Political Connections Decrease Corporate Tax Rates**

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.collapsible {
    color: white;
    cursor: pointer;
    padding: 10px;
    width: 20%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 12px;
}


.content {
    padding: 0px;
    display: none;
    overflow: hidden;
}
</style>
</head>
<body>

<button class="collapsible">Open Abstract</button>
<div class="content">
  <p>For fear of retribution, agencies may enforce rules more leniently against firms with
political connections. I test the argument as it pertains to the enforcement of
tax policy by the Internal Revenue Service (IRS). I compile a novel database of
publicly listed firms, that have hired Members of the US Congress (MCs) in any
capacity in the period 2004-2015. I present evidence that hiring a former MC
decreases the average company's tax rate by a large margin relative the the changes,
the average firm normally experiences. The reduction is short-lived, but yields
meaningful tax-savings for the individual firm, while only modestly impacting public
finances. I show that the effect is driven by the MCs, who have the strongest
political connections, and served in committees with oversight of the IRS. I present
suggestive evidence that firms that hire highly connected MCs substitute away from
traditional forms of lobbying, and are invited to hearings more often. This is likely
to pressure the IRS in their decision-making. These results indicate that firms can
use the revolving door to pursue significant economic rents..</p>
</div>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>

</body>
</html>


 &nbsp; <br><a href="https://github.com/BCEgerod/BCEgerod.github.io/blob/master/papers/TaxDraft.pdf">[pdf]</a>



##Other Projects

**Lobbyists as Government Employees -- Evidence from the Bureaucracy**

*With Josh McCrain, Emory University*




